### ISSUE TITLE
playerVars do not work

### ISSUE THREAD

**Issue by andremacola** [rochestb/jQuery.YoutubeBackground#23]
playerVars do not work, can you check this?

      playerVars: {
        modestbranding: 1,
        autoplay: 1,
        controls: 0,
        showinfo: 0,
        wmode: 'transparent',
        branding: 0,
        rel: 0,
        autohide: 0
      },

**Comment by rochestb** [comment]
I have dug in to this. For me it only occurs when in google chrome and going to a static file. I am essentially finding that Chromecast is firing an error that is preventing the youtube onPlayerReady event. Doesn't look like google plans to fix. Solution is to run the site in a different way than a static file, such as starting a php server `php -S localhost:8000 `

 http://stackoverflow.com/questions/20501010/youtube-api-onplayerready-not-firing
