### ISSUE TITLE
Disable annotations?

### ISSUE THREAD

**Issue by pierlo-upitup** [rochestb/jQuery.YoutubeBackground#25]
Is it possible to turn off YT annotations? 

https://developers.google.com/youtube/player_parameters?hl=en#iv_load_policy

**Comment by rochestb** [comment]
Thanks for the tip! I removed annotations by default. Good call.

The player does support all youtube options. All you have to do is instert them in the playerVars object.

```
$('#module-video').YTPlayer({
  videoId: 'jKCyFB5LmPo',
  playerVars: {
    modestbranding: 0,
    iv_load_policy: 3
  }
});
```
