### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by Giulico** [rochestb/jQuery.YoutubeBackground#26]
Hi,
thank you for this plugin, it's very useful.

Anyway, it returns the following error in the console:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.youtube.com') does not match the recipient window's origin ('https://www.youtube.com').
```

I found this topic:
http://stackoverflow.com/questions/27573017/failed-to-execute-postmessage-on-domwindow-https-www-youtube-com-http 
and it seems that changing the location.protocol to 'https' will fix the error. I tried it on my own project and it works fine without that error.

I would like to use your plugin without edit it, so I want to ask you if you are going to implement this solution (es. as parameter). 

:+1:

**Comment by rochestb** [comment]
Thanks. Please let me know if this push doesn't fix it
https://github.com/rochestb/jQuery.YoutubeBackground/commit/e7dbd0d9dad53a5dd65366a75755288c6899352d
