### ISSUE TITLE
Start option is not working

### ISSUE THREAD

**Issue by pathetix** [rochestb/jQuery.YoutubeBackground#27]
$('#video').YTPlayer({
            start: 1000,
            videoId: 'LSmgKRx5pBo'
        });

Seems like the start option is not working?
Am I doing it wrong?

**Comment by rochestb** [comment]
Try something like this. All Youtube specific arguments should be in the playerVars object.
```
$('#video').YTPlayer({
    videoId: 'LSmgKRx5pBo',
    playerVars {
       'startSeconds': 5
    }
});
```
