### ISSUE TITLE
Causes errors on pages with SSL

### ISSUE THREAD

**Issue by mikejimlarry** [rochestb/jQuery.YoutubeBackground#29]
Line 29 of jquery.youtubebackground.js should be changed from

    tag.src = 'http://www.youtube.com/iframe_api';

to

    tag.src = '//www.youtube.com/iframe_api';

**Comment by rochestb** [comment]
Want to open a PR?

**Comment by rochestb** [comment]
Thanks,
Please let me know if this PR does not fix the issue: 
https://github.com/rochestb/jQuery.YoutubeBackground/commit/e7dbd0d9dad53a5dd65366a75755288c6899352d
