### ISSUE TITLE
firefox and ie  the  a href no working

### ISSUE THREAD

**Issue by m898989** [rochestb/jQuery.YoutubeBackground#30]
Hello i open de example in firefox and IE and the links no work, in google chrome is working
i cant do it working in firefox and IE

![captura2](https://cloud.githubusercontent.com/assets/15054812/10402814/339f18be-6e8d-11e5-96bf-431364bf3381.PNG)
![captura](https://cloud.githubusercontent.com/assets/15054812/10402820/37f21574-6e8d-11e5-9051-9f9066fb8508.PNG)

**Comment by rochestb** [comment]
Hi M787878, Is the issue that there is no hand icon or that when you select a link, the link does not work? Have you tried updaing the z-index on your links?

**Comment by rochestb** [comment]
Im closing this issue, but feel free to put in a PR if you want to add `cursor: pointer`
