### ISSUE TITLE
Load another video on end

### ISSUE THREAD

**Issue by eighthday** [rochestb/jQuery.YoutubeBackground#32]
Is there a better way to load another video into the player? I am using the following, but is is not a seamless change to the next video

    var videoCallbackEvents = function() {
        var player = $('#bg').data('ytPlayer').player;

        player.addEventListener('onStateChange', function(event){
            console.log("Player State Change", event);

            // OnStateChange Data
            if (event.data === 0) {          
              console.log('video ended');
              player.loadVideoById({'videoId': 'UY3S3tO7frM',
               'startSeconds': 9,
               'endSeconds': 10
              });
            }
  
        });
    }

**Comment by rochestb** [comment]
Try creating a play list: https://github.com/rochestb/jQuery.YoutubeBackground/issues/35
