### ISSUE TITLE
start option not wrking.

### ISSUE THREAD

**Issue by giowe** [rochestb/jQuery.YoutubeBackground#33]
the "start" param in options does not work.
I tried also to modify the default value in core module, but still not working... the video still starts from 0

**Comment by rochestb** [comment]
that is strage, are you putting it inside the playerVars object? I just tested it and it worked.

**Comment by rochestb** [comment]
I updated the readme based on this issue. Just added better documentation. Let me knwo if it still doesn't work.

**Comment by giowe** [comment]
OK!!!! very good, it's working! Thanks very much, now the documentation is much more understandable!
