### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Kemar35** [rochestb/jQuery.YoutubeBackground#35]
Thanks for the great work you did! I'm discovering all the possibilities of Youtube API's and Rochestb plugin. 

But I still have some troubles to  Run a Playlist instead of a video ? 

Is someone could help me ? 

Thanks a lot,

Marc

**Comment by rochestb** [comment]
Hey Marc,

Should be something like this.

```
$('#video').YTPlayer({
    fitToBackground: true,
    videoId: 'LSmgKRx5pBo'
    playerVars: {
      modestbranding: 0,
      autoplay: 1,
      controls: 1,
      showinfo: 0,
      branding: 0,
      playerVars: { 'autoplay': 0, 'controls': 1, 'playlist':['your_video_id', 'another_video_id']},
    }
});
```

**Comment by Kemar35** [comment]
Hello,
Thanks for your fast answer!

This code is right, but in my case I wanted to embed a youtube playlist, as in this example: 
https://www.youtube.com/watch?v=SkFaCnDlJLg&index=16&list=PUudKvbd6gvbm5UCYRk5tZKA

So I would need to use the ID of the playlist (here: PUudKvbd6gvbm5UCYRk5tZKA). Not several video ID

The plugin can work with Youtube Playlist ?
I think it could work, because in the suggested videos that appear at the end of the video, if I select a playlist, it is integrated by the plugin. I can even use my control bar to move to the next video etc ...

**Comment by rochestb** [comment]
Try something like this. playerVars contains everything from the youtube iframe api options. 

$('#video').YTPlayer({
    fitToBackground: true,
    videoId: 'LSmgKRx5pBo'
    playerVars: {
      modestbranding: 0,
      autoplay: 1,
      controls: 1,
      showinfo: 0,
      branding: 0,
      playerVars: {
            listType:'playlist',
            list: 'PUudKvbd6gvbm5UCYRk5tZKA'
          }
    }
});

**Comment by Kemar35** [comment]
It works GREAT, 
Thank you !

**Comment by rochestb** [comment]
Good to hear!

**Comment by Tardis1234** [comment]
I've tried using this exact code and it just plays the videoId embed on loop, no playlist.

**Comment by Tardis1234** [comment]
I finally got it to work, but the solution was not nesting the `playerVars` object and removing the `videoId` from both my instance of the player and the default.

$('.video').YTPlayer({
          fitToBackground: true,
          width:$('.video').width(),
          ratio: ratio,
          mute: true,
          repeat: true,
          playerVars: {
            showinfo:0,
            autohide:1,
            modestbranding:1, 
            autoplay: 1, 
            rel: 0,
            listType:'playlist',
            list: 'PUudKvbd6gvbm5UCYRk5tZKA'
         }
});

**Comment by rochestb** [comment]
You need to add the `videoId: 'LSmgKRx5pBo'` otherwise youtube doesn't register which video to start with.

**Comment by Tardis1234** [comment]
So I used your example exactly, but the iFrame never was able to generate
the second level playerVars for some reason.
