### ISSUE TITLE
What heppens with console?

### ISSUE THREAD

**Issue by jack-fdrv** [rochestb/jQuery.YoutubeBackground#37]
Why my console after begins play video looks like a crap? 
<img width="696" alt="231" src="https://cloud.githubusercontent.com/assets/4230282/11888074/a4b23dd8-a542-11e5-8c00-640f8db43127.png">

**Comment by rochestb** [comment]
This is an existing bug in chrome and the youtube api. It has nothing to do with the jquery plugin itself. I think it also has to do with chrome cast plugin.

http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi
