### ISSUE TITLE
Duration bar

### ISSUE THREAD

**Issue by Kemar35** [rochestb/jQuery.YoutubeBackground#39]
-- Sorry to create an Issue, this isn't really an issue --

I'm trying to create my own Youtube controle bar with Youtube-API. It works great. However, I have some troubles to link youtube player data's (Duration & Current Time : https://developers.google.com/youtube/iframe_api_reference?hl=fr#Retrieving_video_information ) to my slider bar (MDL slider : http://www.getmdl.io/components/index.html#sliders-section)

The selector stay at the middle of the bar slider...

Could someone help ? (link to the project, please keep it secret for now : http://mdaniel.fr/swirly/la-belle-musique.html - Press F11 for a better experience, and Chrome is more clean with it)

-- Code --

HTML : 
```html
<input class="mdl-slider mdl-js-slider" type="range" id="s0" min="0" max="???" value="???" step="1">
```

JS : 
```javascript
    function setCursor() {
        $("#s0").attr({
                              "max" : function(){ var player=$('#video').data('ytPlayer').player; return player.getDuration(); },
                              "value" : function(){ var player=$('#video').data('ytPlayer').player; return player.getCurrentTime(); }
                           });
    console.log("1 second");
    setTimeout(setCursor, 1000);
}
```

Thanks,

Marc

**Comment by rochestb** [comment]
Since this plugin lets you leverage the youtube api try something like this: http://stackoverflow.com/questions/25593156/youtube-custom-progressbar-using-youtube-iframe-api-and-jquery-not-working
