### ISSUE TITLE
OSX safari bugs

### ISSUE THREAD

**Issue by msbtterswrth** [rochestb/jQuery.YoutubeBackground#43]
Doesn't loop (and consequently shows related videos) in Safari on OSX. I had to specifically add in the loop and playlist parameters from the youtube api to make it work, but it's still jumpy.

Also, you might want to add something in that prevents click events. If you accidentally click the bg you will pause the video and on hover the youtube logo shows. Those can both be prevented by adding pointer-events:none to the css.

**Comment by ferman** [comment]
@msbtterswrth Where exactly did you add the loop parameter?

I was guessing it was to go inside the playerVars area but I had no luck.

`$('.video-bg').YTPlayer({
            fitToBackground: true,
            videoId: 'QZkd6odjinM',
            repeat: 'true',
            playerVars: {
                modestbranding: 0,
                autoplay: 1,
                controls: 1,
                loop: 1,
                showinfo: 0,
                branding: 0,
                rel: 0,
                autohide: 0,
                start: 0
            }
        });`

**Comment by msbtterswrth** [comment]
This is what i ended up using: 
`$('.bg-video').YTPlayer({
        fitToBackground: true,
        repeat:true,
        videoId: 'ArIsfqzGoEc',
        playerVars: {
            autoplay: 1,
            controls: 0,
            showinfo: 0,
            wmode: 'transparent',
            branding: 0,
            rel: 0,
            autohide: 1,
            loop:1,
            playlist: 'ArIsfqzGoEc'
          }
    });`

The loop param only works with playlists, so you have to add that in as well. It's a bit hacky but it's the only solution I could come up with.
