### ISSUE TITLE
Version inconsistent problem

### ISSUE THREAD

**Issue by kennynaoh** [rochestb/jQuery.YoutubeBackground#44]
Hello @rochestb ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there are some version problem.
In latest git tag v1.0.4, the version in ```src/jquery.youtubebackground.js``` shows 1.0.1, and the version in ```bower.json``` is also 1.0.1.
Please confirm this and fix it.
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7837

**Comment by rochestb** [comment]
Hey @kennynaoh i went ahead and updated the version in bower.json. Would love to get the project on a cdn, thanks!

**Comment by kennynaoh** [comment]
Hi @rochestb ,
I think the version in git tag v1.0.4 still shows version 1.0.1.
You only updated the version in master branch.
Please confirm this.
Thanks!

**Comment by rochestb** [comment]
Okay give it a try again. I pushed it to v1.0.5.

Thanks,
Benton

On Sun, May 15, 2016 at 2:58 AM, naoh <notifications@github.com> wrote:

> Hi @rochestb <https://github.com/rochestb> ,
> I think the version in git tag v1.0.4 still shows version 1.0.1.
> You only updated the version in master branch.
> Please confirm this.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rochestb/jQuery.YoutubeBackground/issues/44#issuecomment-219274060>
>



-- 

Benton Rochester
Cell: (303) 521-5311
Web: ImBenton.com
Linkedin: imBenton <http://www.linkedin.com/in/imbenton>

**Comment by kennynaoh** [comment]
oops!
I think the version in js file need to be the same as the git tag.
The version in ```src/jquery.youtubebackground.js``` in git tag v1.0.5 you mention is version 1.0.4.
It should be updated to version 1.0.5.
Please confirm that.
Thanks very much!
