### ISSUE TITLE
Why is mobile not supported?

### ISSUE THREAD

**Issue by louiswalch** [rochestb/jQuery.YoutubeBackground#49]
I am a little confused why mobile is not supported? The standard iframe embed from YouTube works fine on mobile devices and you are embedding the player via iframe. This should be supposed.

**Comment by rochestb** [comment]
This an issue with Youtube as videos can't be played without being full screen. The only thing you can do is add a fallback image for mobile devices.

**Comment by williamboman** [comment]
What's the best way of detecting devices that are not compatible?

**Comment by nam-co** [comment]
Hi Benton, thanks for the cool script, now that <video playsinline> is allowed in mobile, is it possible to use the script in mobile?

Thanks for your help
