### ISSUE TITLE
Vertical align

### ISSUE THREAD

**Issue by galechus** [rochestb/jQuery.YoutubeBackground#53]
Hi,
i add css vertical align in video container.

You solution:
`.ytplayer-container {
    position: absolute;
    top: 0;
    z-index: -1;
}`

My solution:
`.ytplayer-container {
    position: absolute;
    top: 50%;
    z-index: -1;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
  }`

**Comment by rochestb** [comment]
good call.
