### ISSUE TITLE
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.youtube.com’) does not match the recipient window’s origin 

### ISSUE THREAD

**Issue by BenjoJ** [rochestb/jQuery.YoutubeBackground#64]
Hi, I am receiving the error below, and no matter how much googling I do I can't clear it.

> Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.youtube.com’) does not match the recipient window’s origin (‘http://localhost’).

`		$(document).ready(function () {
			$('#video').YTPlayer({
				fitToBackground: true,
				videoId: 'myvideoID'
			});
		})`

Tested in FF and Chrome and same error message in both.

Encountered this before? Let me know if you need any more info.

**Comment by skappel** [comment]
Hi guys, any progress on this? We are experiencing the same problem.

Cheers

**Comment by kbrookes** [comment]
Same here

**Comment by MindwireAustralia** [comment]
Having the same issue as well.

**Comment by rochestb** [comment]
I think https is the trick here but its an issue with the youtube api

**Comment by skappel** [comment]
We do have an SSL certificate installed on the website, but the issue still remains. I think Youtube API may be the problem.

**Comment by kbrookes** [comment]
I can confirm this is happening on sites with an SSL cert and using YouTube links with https - so as per previous comments, probably an API issue.
