### ISSUE TITLE
Don't play background video on Ipad

### ISSUE THREAD

**Issue by duza** [rochestb/jQuery.YoutubeBackground#75]
Hello. I went on your [example](http://rochestb.github.io/jQuery.YoutubeBackground/) using Ipad Model A1490 version os 9.3.2(13F69) Chrome 63.03239.73 and noticed that the background video doesn't play. Could you research this problem? Thank you in advance.

**UPD**: I debugged this issue and discovered in console such messages
![Image of error messages](https://user-images.githubusercontent.com/6421512/42500686-a13143b4-843a-11e8-94a2-5d16fd5af94a.png)
Problem locates in `www-widgetapi.js` on 96 line:
```js
h.B = function(a) {
        a.id = this.g;
        a.channel = "widget";
        a = xa(a);
        var b = this.b;
        var c = Ba(this.a.src);
        b = 0 == c.indexOf("https:") ? [c] : b.a ? [c.replace("http:", "https:")] : b.c ? [c] : [c, c.replace("http:", "https:")];
        if (!this.a.contentWindow)
            throw Error("The YouTube player is not attached to the DOM.");
        for (c = 0; c < b.length; c++)
            try {
HERE --->>>   this.a.contentWindow.postMessage(a, b[c])
            } catch (d) {
                if (d.name && "SyntaxError" == d.name)
                    Ha(d, "WARNING");
                else
                    throw d;
            }
    };
```
I don't know... maybe you need use `origin` parameter in `playerVars`...or maybe it is the problem of youtube api ?

**Comment by rochestb** [comment]
Unfortunately, this plugin doesn't work for any ios devices. I think its an issue with how Apple handles iframed videos.
